name: uuzTicket-Actions

on: [push]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Init laravel
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist'
        php artisan key:generate
        mkdir -p database
        touch database/database.sqlite

    - name: Starting unit test
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Code coverage reports
      uses: codecov/codecov-action@v1
      with:
        - token: ${{ secrets.CODECOV_TOKEN }}
      run: |
        vendor/bin/codacycoverage clover ./coverage.xml
